### ISSUE TITLE
Exporting request and response from subscription services

### ISSUE THREAD

**Issue by eduherminio** [afimb/siri-validator#3]
Using the console mode, I am being capable of exporting input and output XML to files **in an specific directory** by running:
`ETClient -Line			 -in trash/ET_Req	 	-out trash/ET_Res		-d ./trash`
`SMClient -stopId 206 	 -in trash/SM_Req	 	-out trash/SM_Res	 	-d ./trash`

But I can't find the right command sequence to do the same with subscription requests & responses, having tried something like the following:
`Subscribe -Notify /localhost:8081/ -ValidUntil 2017/07/28-13:00 -Service ETClient -Line -in trash/ET_Req  -out trash/ET_Res  -d ./trash`

Not even with the simple unsubscribe command
`Unsubscribe -SubscriptionId all -in trash/UnSub_req  -out trash/UnSub_res	  -d ./trash`
`Unsubscribe -SubscriptionId all -in Unsub_Req 	-out Unsub_Res		-d ./trash`

They both show the whole XML in the console and write request and response files, using default names, in `.` insted of in `./trash`.

What am I missing?
Thanks in advance,

Eduardo

PD: In case it's relevant, I'm trying it on Windows.

**Comment by metienne** [comment]
unfortunately, SubscribeCommand class don't parse -in , -out and -d options;
it can be added on parseArgs method using same code as in SMCommand or ETCommand for example 
You are allowed to do it and send the community a pull request or ask Chouette forum (http://forum.chouette.mobi/) for an upgrade
-in, -out and -d options must be set in the command syntax before the -service option
Notification traces are also saved in default directory; no options are at this day ready to manage another directory.

**Comment by eduherminio** [comment]
I would consider giving it a try, but I'm afraid I've barely no java knowledge so it would take me more time than I have available right now. Maybe some day.
I'm registering in the forum, though.
Thanks again @metienne.
